console.group('Верстка main');
  console.group('Вёрстка соответствует макету при ширине экрана 1280px');
    console.log('блок <header>: +2');
    console.log('блок Not only: +2');
    console.log('блок About: +2');
    console.log('блок Our Friends: +2');
    console.log('блок Help: +2');
    console.log('блок In addition: +2');
    console.log('блок <footer>: +2');
    console.log('итого: +14');
  console.groupEnd();
  console.group('Вёрстка соответствует макету при ширине экрана 768px');
    console.log('блок <header>: +2');
    console.log('блок Not only: +2');
    console.log('блок About: +2');
    console.log('блок Our Friends: +2');
    console.log('блок Help: +2');
    console.log('блок In addition: +2');
    console.log('блок <footer>: +2');
    console.log('ИТОГО +14');
  console.groupEnd();
  console.group('Вёрстка соответствует макету при ширине экрана 320px');
    console.log('блок <header>: +2');
    console.log('блок Not only: +2');
    console.log('блок About: +2');
    console.log('блок Our Friends: +2');
    console.log('блок Help: +2');
    console.log('блок In addition: +2');
    console.log('блок <footer>: +2');
    console.log('ИТОГО +14');
  console.groupEnd();
console.groupEnd();
console.group('Верстка our pets')
  console.group('Вёрстка соответствует макету при ширине экрана 1280px');
    console.log('блок <header>: +2');
    console.log('блок Our Friends: +2');
    console.log('блок <footer>: +2');
    console.log('ИТОГО +6');
  console.groupEnd();
  console.group('Вёрстка соответствует макету при ширине экрана 768px');
    console.log('блок <header>: +2');
    console.log('блок Our Friends: +2');
    console.log('блок <footer>: +2');
    console.log('ИТОГО +6');
  console.groupEnd();
  console.group('Вёрстка соответствует макету при ширине экрана 320px');
    console.log('блок <header>: +2');
    console.log('блок Our Friends: +2');
    console.log('блок <footer>: +2');
    console.log('ИТОГО +6');
  console.groupEnd();
console.groupEnd();
console.log('При масштабировании вплоть до 320px не появляется горизонтальная полоса прокрутки, белые поля справа от блоков, контент не обрезается и не удаляется +20')
console.group('Верстка резиновая');
  console.log('main +4');
  console.log('our pets +4');
  console.log('ИТОГО: +8');
console.groupEnd();
console.log('Появляется иконка бургер-меню на разрешении меньше 768px +4');
console.log('Верстка валидная +8');
console.log('ИТОГО ЗА ЗАДАНИЕ +100');